#!/usr/bin/env python
"""Generate or validate the example command and marker reference."""

from __future__ import annotations

import argparse
import re
import subprocess
import sys
import tomllib
from pathlib import Path

MOJIBAKE = ("â€“", "â€œ", "â€", "Ã", "�")
STALE_REFERENCES = (
    "examples/",
    "L3_T6_property-based.md",
    "L3_T8_non-functional.md",
    "L3_T10_health_and_metrics.md",
)


def commands(root: Path) -> list[tuple[str, str]]:
    result = subprocess.run(
        ["just", "--list", "--unsorted"],
        cwd=root,
        capture_output=True,
        check=False,
        text=True,
    )
    if result.returncode:
        raise ValueError(result.stderr.strip() or "just --list failed")
    values: list[tuple[str, str]] = []
    for line in result.stdout.splitlines()[1:]:
        match = re.match(r"\s{4}([^#]+?)(?:\s+#\s*(.*))?$", line)
        if match:
            values.append((match.group(1).strip(), (match.group(2) or "").strip()))
    if not values:
        raise ValueError("no recipes found")
    return values


def markers(root: Path) -> list[tuple[str, str]]:
    config = tomllib.loads((root / "pyproject.toml").read_text(encoding="utf-8"))
    declarations = config["tool"]["pytest"]["ini_options"]["markers"]
    values: list[tuple[str, str]] = []
    for declaration in declarations:
        name, description = declaration.split(":", 1)
        values.append((name.strip(), description.strip()))
    return values


def render(root: Path) -> str:
    lines = [
        "# Generated command and marker reference",
        "",
        "<!-- Generated by scripts/docs_reference.py; do not edit by hand. -->",
        "",
        "## Commands",
        "",
        "| Recipe | Purpose |",
        "| --- | --- |",
    ]
    for recipe, purpose in commands(root):
        lines.append(f"| `{recipe}` | {purpose or 'Default recipe.'} |")
    lines.extend(
        [
            "",
            "## Pytest markers",
            "",
            "| Marker | Meaning |",
            "| --- | --- |",
        ]
    )
    for marker, meaning in markers(root):
        lines.append(f"| `{marker}` | {meaning} |")
    return "\n".join(lines) + "\n"


def validate_repository(repository: Path) -> list[str]:
    errors: list[str] = []
    for path in sorted(repository.rglob("*.md")):
        if any(part in {".venv", ".uv-cache"} for part in path.parts):
            continue
        text = path.read_text(encoding="utf-8")
        for token in MOJIBAKE:
            if token in text:
                errors.append(f"{path.relative_to(repository)} contains mojibake token {token!r}")
        for stale in STALE_REFERENCES:
            if stale in text:
                errors.append(f"{path.relative_to(repository)} contains stale reference {stale}")
        if "case_study" not in path.parts:
            for raw_reference in re.findall(r"`([^`\n]+\.md(?:#[^`\n]+)?)`", text):
                reference = raw_reference.split("#", 1)[0]
                if "*" in reference or reference.startswith("/"):
                    continue
                target = (path.parent / reference).resolve()
                if not target.is_file():
                    errors.append(
                        f"{path.relative_to(repository)} links to missing {raw_reference}"
                    )
    return errors


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--root", type=Path, default=Path.cwd())
    parser.add_argument("--write", action="store_true")
    args = parser.parse_args(argv)
    root = args.root.resolve()
    output = root / "generated-reference.md"
    try:
        expected = render(root)
        if args.write:
            output.write_text(expected, encoding="utf-8")
        elif not output.exists() or output.read_text(encoding="utf-8") != expected:
            print("generated-reference.md is stale; run just docs-generate", file=sys.stderr)
            return 1
        errors = validate_repository(root.parent)
    except (OSError, KeyError, TypeError, ValueError, tomllib.TOMLDecodeError) as error:
        print(f"documentation reference error: {error}", file=sys.stderr)
        return 2
    for error in errors:
        print(error, file=sys.stderr)
    return 1 if errors else 0


if __name__ == "__main__":
    raise SystemExit(main())
